# Generated by Django 4.2.5 on 2023-12-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='certificate1_name',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='certificate1_number',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='certificate1_organizer',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='certificate1_year',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='certificate_count',
        ),
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='role',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('organizer', models.CharField(max_length=100)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='main.caregiverprofile')),
            ],
        ),
    ]
