# Generated by Django 4.2.5 on 2023-12-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workingday_remove_caregiverprofile_certificate1_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='available_working_days',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='available_working_days',
            field=models.ManyToManyField(to='main.workingday'),
        ),
    ]
